### ISSUE TITLE
trizen crashes after new installation

### ISSUE THREAD

**Issue by woodyl** [trizen/trizen#189] opened 2018-11-09 22:06 UTC
I installed trizen for the first time.  It crashes immediately on launch with this message:
`Can't use string ("version::regex::LAX_DOTTED_DECIM"...) as a SCALAR ref while "strict refs" in use at /usr/share/perl5/core_perl/version.pm line 21.
Compilation failed in require at /usr/share/perl5/core_perl/experimental.pm line 5.
BEGIN failed--compilation aborted at /usr/share/perl5/core_perl/experimental.pm line 5.
Compilation failed in require at /usr/bin/trizen line 48.
BEGIN failed--compilation aborted at /usr/bin/trizen line 48.`

**Comment by trizen** [comment] 2018-11-09 22:29
I cannot reproduce this issue.

There seems to be something wrong in the file `/usr/share/perl5/core_perl/version.pm`. Can you post here the output of `head -21 /usr/share/perl5/core_perl/version.pm`?

One potential solution would be to try to reinstall `perl`.

**Comment by woodyl** [comment] 2018-11-09 22:53
I did manually delete and reinstall perl, but that didn't fix it.

Here's the output you requested:
```
 head -21 /usr/share/perl5/core_perl/version.pm
#!perl -w
package version;

use 5.006002;
use strict;
use warnings::register;
if ($] >= 5.015) {
    warnings::register_categories(qw/version/);
}

our $VERSION = 0.9923;
our $CLASS = 'version';
our (@ISA, $STRICT, $LAX);

# avoid using Exporter
require version::regex;
*version::is_lax = \&version::regex::is_lax;
*version::is_strict = \&version::regex::is_strict;
*LAX = \$version::regex::LAX;
*LAX_DECIMAL_VERSION = \$version::regex::LAX_DECIMAL_VERSION;
*LAX_DOTTED_DECIMAL_VERSION = \$version::regex::LAX_DOTTED_DECIMAL_VERSION;
```

**Comment by trizen** [comment] 2018-11-09 23:51
If you think it's not a local issue, please consider reporting this issue at: https://bugs.archlinux.org/?project=1&string=perl

I'm closing this now, as it's not really a `trizen` related issue.

**Closed by trizen** 2018-11-09 23:51 UTC
